---
title: "Support the show"
permalink: "/support-the-show.html"
---

Here at BlahCade we don’t use any freemium model to fund the show.
We produce the show each week because we are passionate about digital and physical Pinball.

== Shout us a coffee?

If you want to shout us a coffee to say thanks for the show, you can send a donation through https://www.paypal.me/blahcade/5[PayPal]. 

We don't charge for the show, so we get a real buzz when people donate real money to us. 

Thank you so much!

++++
<a target="_blank" class="btn btn-danger" href="https://www.paypal.me/blahcade/5">Caffeinate the hosts!</a>
++++

== Buy some sweet merch?

https://www.redbubble.com/shop/ap/33899008[Redbubble] ships all over the world, but has local production houses. 
That keeps the cost of shipping down for you so you can buy more stuff, not more shipping.

All profits from merchandise sales go right back into the show. 
Every cent.

++++
<a target="_blank" class="btn btn-danger" href="https://www.redbubble.com/shop/ap/33899008">Grab some threads!</a>
++++

== Become a show sponsor!

BlahCade is a unique platform for your pinball, video game, or general geek-related company to broaden their reach to a targeted audience.

A show sponsor like you can provide a financial tithe each month, or offer products and services as prizes for competitions.

We’ll feature your company in all episode posts that you sponsor, and will keep your information there as a historical record that you’re a good egg and are passionate about supporting the pinball industry.

Contact blahblahblahcade@gmail.com to start the conversation.