name: Mundana
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: ''
disqus: demowebsite
email: wowthemesnet@gmail.com
mailchimp-list: >-
  https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
  - _pages
permalink: '/:title/'
plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
authors:
  chris:
    name: Chris Friebus
    site: 'https://www.wowthemes.net'
    avatar: /assets/images/chris.jpeg
    bio: >-
      Host of the BlahCade Pinball Podcast, camera assistant for TV & film, wannabe screenwriter
    email: shutyertraps@gmail.com
    twitter: 'https://twitter.com/shutyertraps'
  jared:
    name: Jared Morgan
    site: 'https://jaredleonmorgan.net'
    avatar: /assets/images/jared.jpeg
    bio: >-
      Co-host of the BlahCade Pinball Podcast, Technical Writer, VR junkie.
    email: jaredleonmorgan@gmail.com
    twitter: 'https://twitter.com/jaredmorgs'
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: jared
      avatar: /assets/images/jared.jpeg
  - scope:
      path: _pages
    values:
      layout: page
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
url: ''
