name: BlahCade Pinball Podcast
description: 'The premier commercial digital pinball podcast'
logo: assets/images/logo-large.png
favicon: assets/images/favicon.ico
baseurl: ''
disqus: blahcade
email: blahblahblahcade@gmail.com
mailchimp-list: 
include:
  - _pages
permalink: '/:title/'
plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
authors:
  chris:
    name: Chris Friebus
    site: 
    avatar: assets/images/chris.png
    bio: >-
      Co-host of the BlahCade Pinball Podcast, camera assistant for TV & film, wannabe screenwriter.
    email: shutyertraps@gmail.com
    twitter: 'https://twitter.com/shutyertraps'
  jared:
    name: Jared Morgan
    site: 'https://jaredleonmorgan.net'
    avatar: assets/images/jared.jpg
    bio: >-
      Co-host of the BlahCade Pinball Podcast, Technical Writer, VR junkie.
    email: jaredleonmorgan@gmail.com
    twitter: 'https://twitter.com/jaredmorgs'
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: jared
      avatar: assets/images/jared.jpg
  - scope:
      path: _pages
    values:
      layout: page
markdown: kramdown
asciidoctor:
  attributes:
    imagesdir: /assets/images
highlighter: rouge
paginate: 10
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
url: ''
